// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nsebmqyccdkskutgvhqm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5zZWJtcXljY2Rrc2t1dGd2aHFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzOTcyNTIsImV4cCI6MjA2MDk3MzI1Mn0.W-0ltnB9eT03d0GJzWb163heoS2xjR2FI-Vt-P-KY_c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);